### ISSUE TITLE
Option to not count previous floors under reached

### ISSUE THREAD

**Issue by Jaksuhn** [wrath16/MapPartyAssist#2]
Say you get floor 5. In the `/mpartystats` screen, that will show a +1 under "reached [1st/2nd/3rd/4th/5th] chamber". Instead of just +1 on reached 5th.

I've had a spreadsheet of my thief data for a while now. I input which floor I was kicked out on. It's very easy to extrapolate from that to to your format of data to get percentages. While it's possible to reverse your data to figure out which floor I was kicked out on, it's a lot of work.

A raw data dump of which floor you were kicked out on in a session would alternatively be really helpful.

**Comment by wrath16** [comment]
Yeah, I can make that a config option, no problem.

**Comment by wrath16** [comment]
Implemented under config option "Tally checkpoint totals" "By last checkpoint only".
