### ISSUE TITLE
display ejection sequence

### ISSUE THREAD

**Issue by Jaksuhn** [wrath16/MapPartyAssist#4]
One more stat request. Above/Below the endChambers counts, an option to display the raw sequence, comma separated.

i.e. Ejection Sequence: 1, 3, 2, 2, 4, 5, 1, 1, 1, 3, 7, 3

**Comment by wrath16** [comment]
Check /mpartydutyresults -> 'Copy CSV' if this solves your needs.

**Comment by Jaksuhn** [comment]
Ah, yes it does. Didn't think that'd have the raw data. My mistake for not just testing that
