### ISSUE TITLE
Feature Request - Optional "Map Links by Zone" window

### ISSUE THREAD

**Issue by StackBLU** [wrath16/MapPartyAssist#6]
Could an option be created to optionally open the "Map Links by Zone" window when opening mparty, instead of it always opening? I find I never use this window, so it is just extra clutter on the screen.

**Comment by wrath16** [comment]
Sure I can add that as an option.

**Comment by wrath16** [comment]
This function is available under the option "Hide 'Map Links by Zone'" in `/mpartyconfig`
