### ISSUE TITLE
Feature Request: send map payload button 

### ISSUE THREAD

**Issue by rrbailey89** [wrath16/MapPartyAssist#8]
As far as I can tell currently you have to click a button then manually type in chat <flag>. It would be neat if there was a button that would send the next treasure map location directly to chat. I think This would prevent the users treasure map location from being overwritten in the plugin when they share it.

**Comment by wrath16** [comment]
There is an option under `/mpartyconfig` to prevent overwriting of map links.

**Comment by rrbailey89** [comment]
> There is an option under `/mpartyconfig` to prevent overwriting of map links.

I see that however there is still an extra step created.

Click button to bring flag up on map
Type in party chat to share flag. 

When there could be a button that sends the map payload on the first click to party chat.

**Comment by wrath16** [comment]
Dalamud generally frowns upon automating server interactions, but I'll explore what can be done.

**Comment by rrbailey89** [comment]
> Dalamud generally frowns upon automating server interactions, but I'll explore what can be done.

Yea I understand that, but I honestly do not see much difference in for example using gather buddy and typing /gather flax... Then the plugin automatically switching to botanist AND automatically teleporting to the nearest aetheryte. 

So hopefully you can implement a button that when clicked sends the map payload to chat and the powers that be are happy with it 😎
